### ISSUE TITLE
The auto farm

### ISSUE THREAD

**Issue by Adam123158** [SmClan/Credits_Bot#1]
$auto 100credits in minute

**Comment by SmClan** [comment]
**اهلًا ، نظرًا لان المكتبه قيد التطوير حاليًا البوت يعمل بكل جهده لتطوير المكتبه وجعل قدر الكريدتس اكبر وإتاحة المزيد من الفرص لمزيد من الاعضاء لاستخدام الامر بسهوله تامه وبدون وقت**

> شكرًا على المبادره
