### ISSUE TITLE
ثغرات للمكتبه

### ISSUE THREAD

**Issue by Adam123158** [SmClan/Credits_Bot#3]
اريد ثغره auto farm$ لتجميع100 كردت ب 10 دقائق وايضا اريد 50 كردت كل خمس دقائق

**Comment by SmClan** [comment]
**نظرًا لان الفارم مدته دقيقه لجمع 70 كريدتس ، فطلبك غير ممكن .. يمكنك مراجعة كيفية الإستخدام والتحديثات الجديده لتتمكن من معرفة طبيعة الأوامر وكيف يتم إستخدامُها بشكل صحيح** يمكن الذهب من هنا [https://github.com/SmClan/Credits_Bot](url)
